## **Problem Context**
#### **Description:** 
- Using NLP and machine learning, make a model to identify toxic comments from the Talk edit pages on Wikipedia. Help identify the words that make a comment toxic.

#### **Statement:**  
- Wikipedia is the world’s largest and most popular reference work on the internet with about 500 million unique visitors per month. It also has millions of contributors who can make edits to pages. The Talk edit pages, the key community interaction forum where the contributing community interacts or discusses or debates about the changes pertaining to a particular topic. 
  - Wikipedia continuously strives to help online discussion become more productive and respectful. You are a data scientist at Wikipedia who will help Wikipedia to build a predictive model that identifies toxic comments in the discussion and marks them for cleanup by using NLP and machine learning. Post that, help identify the top terms from the toxic comments. 

#### **Analysis to be done:**
- Build a text classification model using NLP and machine learning that detects toxic comments.

#### **Data Dictionary:** 
- id: identifier number of the comment
- comment_text: the text in the comment
- toxic: 0 (non-toxic) / 1 (toxic)

#### **Steps to perform:**
- Cleanup the text data, using TF-IDF convert to vector space representation, use Support Vector Machines to detect toxic comments. 
- Finally, get the list of top 15 toxic terms from the comments identified by the model.

#### **Sub-Tasks:** 
- Load the data using read_csv function from pandas package
- Get the comments into a list, for easy text cleanup and manipulation
- Cleanup: 
  - Using regular expressions, remove IP addresses
  - Using regular expressions, remove URLs
  - Normalize the casing
  - Tokenize using word_tokenize from NLTK
  - Remove stop words
  - Remove punctuation
  - Define a function to perform all these steps, you’ll use this later on the actual test set
- Using a counter, find the top terms in the data.
  - Can any of these be considered contextual stop words?
  - Words like “Wikipedia”, “page”, “edit” are examples of contextual stop words
  - If yes, drop these from the data
- Separate into train and test sets
  - Use train-test method to divide your data into 2 sets: train and test
  - Use a 70-30 split
- Use TF-IDF values for the terms as feature to get into a vector space model
  - Import TF-IDF vectorizer from sklearn
  - Instantiate with a maximum of 4000 terms in your vocabulary
  - Fit and apply on the train set
  - Apply on the test set
- Model building: Support Vector Machine
  - Instantiate SVC from sklearn with a linear kernel
  - Fit on the train data
  - Make predictions for the train and the test set
- Model evaluation: Accuracy, recall, and f1_score
  - Report the accuracy on the train set
  - Report the recall on the train set:decent, high, low?
  - Get the f1_score on the train set
- Looks like you need to adjust  the class imbalance, as the model seems to focus on the 0s
  - Adjust the appropriate parameter in the SVC module
- Train again with the adjustment and evaluate
  - Train the model on the train set
  - Evaluate the predictions on the validation set: accuracy, recall, f1_score
- Hyperparameter tuning
  - Import GridSearch and StratifiedKFold (because of class imbalance)
  - Provide the parameter grid to choose for ‘C’
  - Use a balanced class weight while instantiating the Support Vector Classifier
- Find the parameters with the best recall in cross validation
  - Choose ‘recall’ as the metric for scoring
  - Choose stratified 5 fold cross validation scheme
  - Fit on the train set
- What are the best parameters?
- Predict and evaluate using the best estimator
  - Use best estimator from the grid search to make predictions on the test set
  - What is the recall on the test set for the toxic comments?
  - What is the f1_score?
- What are the most prominent terms in the toxic comments?
  - Separate the comments from the test set that the model identified as toxic
  - Make one large list of the terms
  - Get the top 15 terms












## **Aquire the data**

In [ ]:
!wget https://raw.githubusercontent.com/snikhil17/NLP_course_Simplilearn/main/capstone_project/train.csv

--2021-12-09 12:23:29--  https://raw.githubusercontent.com/snikhil17/NLP_course_Simplilearn/main/capstone_project/train.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2102032 (2.0M) [text/plain]
Saving to: ‘train.csv’

train.csv           100%[===================>]   2.00M  --.-KB/s    in 0.06s   

2021-12-09 12:23:29 (33.4 MB/s) - ‘train.csv’ saved [2102032/2102032]



## **Loading required Libraries**

In [ ]:
! python3 -m spacy download en_core_web_sm

In [1]:
import pandas as pd
import numpy as np
import nltk
import matplotlib.pyplot as plt
import re
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

from nltk.corpus import wordnet
import string
from nltk.stem import WordNetLemmatizer

nltk.download('words')

from nltk.corpus import stopwords
nltk.download('stopwords')

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import spacy
nlp = spacy.load('en_core_web_sm')


from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.model_selection import GridSearchCV, StratifiedKFold

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [19]:
df = pd.read_csv('train.csv')
df.head()

id                                       comment_text  toxic
0  e617e2489abe9bca  "\r\n\r\n A barnstar for you! \r\n\r\n  The De...      0
1  9250cf637294e09d  "\r\n\r\nThis seems unbalanced.  whatever I ha...      0
2  ce1aa4592d5240ca  Marya Dzmitruk was born in Minsk, Belarus in M...      0
3  48105766ff7f075b      "\r\n\r\nTalkback\r\n\r\n Dear Celestia...  "      0
4  0543d4f82e5470b6  New Categories \r\n\r\nI honestly think that w...      0

## **Cleaning Helper Functions** 
- **Function for decontracted and removing IP adresses and other expressions using Regex**
  - words like don't , won't etc will be converted to do not, will not etc.
  - Emojis, additional lines, email-addresses, website names etc are removed here.
- **Removed words like ``no, not, nor`` from english stopwords**
- **Removing Non-English Words**
  - whatever words nltk corpus has, if given word is in that corpus we will consider the word, else replace with blank.
- **Removing Contextual Stopwords**
  - Using POS-tagging feature of Spacy, removed words which were Pronoun, punctuation, number, adverb  etc.
  - Lemmatizing th words and checking if the given word exist in the list of words needs to be removed (contextual words: obtained after checking the word counts)
- **Remaining Preprocessing of text**
  - Combining all the above functions to use as analyzer in TF-IDF vectorizer. 

In [20]:
"""Functions to clean text using Regex"""
ip_addr_regex = re.compile(r'\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b')
emoji_pattern = re.compile("["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           "]+", flags=re.UNICODE)
def regex_cleaning(phrase):
    # specific
    phrase = re.sub(r"won\'t", "will not", phrase)
    phrase = re.sub(r"can\'t", "can not", phrase)

    # general
    phrase = re.sub(r"n\'t", " not", phrase)
    phrase = re.sub(r"\'re", " are", phrase)
    phrase = re.sub(r"\'s", " is", phrase)
    phrase = re.sub(r"\'d", " would", phrase)
    phrase = re.sub(r"\'ll", " will", phrase)
    phrase = re.sub(r"\'t", " not", phrase)
    phrase = re.sub(r"\'ve", " have", phrase)
    phrase = re.sub(r"\'m", " am", phrase)
    phrase = re.sub(r"[^a-zA-Z0-9]+", " ", phrase)
    phrase = re.sub(r"\r\n", "", phrase)            # Removing additional line
    phrase = re.sub(r"\n", "", phrase)              # Removing additional line 
    phrase = re.sub(r"\S*@\S*\s?", "", phrase)      # Removing email-addresses 
    phrase = re.sub(r'http\S+', '', phrase)         # Removing website links
    phrase = re.sub(ip_addr_regex, "", phrase)      # Removing IP address link.
    phrase = emoji_pattern.sub(r'', phrase)         # Removing Emojis
    
    return phrase.lower() 

"""Ammending Stopwords list"""
stop_words = stopwords.words('english')
for i in ['nor', 'not', 'no']:
  stop_words.remove(i)

"""Removing Non-English Words"""
nltk_words = set(nltk.corpus.words.words())
def only_eng(row):
  for word in row:
    if word in nltk_words or not word.isalpha():
      word = word
    else:
      word = ""
  return row

# """Helper function for lemmatization_check"""
def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

# """Extracting Lemmatized word to take care that words like page, paged, pages can be removed at once."""

def lemmatization_check(word):
  word_pos = nltk.pos_tag(word)
  lemma_word = lemmaObject.lemmatize(word,get_wordnet_pos(word))
  return lemma_word

"""Removing Contextual Stopwords"""
# 'ADJ',
lemmaObject = WordNetLemmatizer()
pos_taggings_to_remove = ['DET', 'ADP','ADV','AUX', 'SCONJ',  'INTJ','PUNCT', 'NUM',  'SPACE', 'X']
some_words_to_remove = ['you', 'wikipedia', 'wiki' ,'edit', 'page', 'would', 'article', 'articles','page', 'edits', 'user']
def remove_contextual_stopwords(row):
  row= row.lower()  
  final_row = []
  row = "".join([lemmaObject.lemmatize(word[0],get_wordnet_pos(word[1])) for word in nltk.pos_tag(row)])
  row = nlp(row)
  for word in row:    
    if word.pos_ not in pos_taggings_to_remove and word.text not in some_words_to_remove:
      final_row.append(word.text)
    else:
      continue
  return " ".join(final_row)

"""Remaining Preprocessing of text"""
def final_preprocessing(document):
  document_regex_cleaned = regex_cleaning(document)
  noNonEnglishWords = only_eng(document_regex_cleaned)
  words = [" ".join(nltk.word_tokenize(title)) for title in noNonEnglishWords.split()]                                         # Word Tokenization0
  wordWithoutStopwords = [word for word in words if word not in stop_words if len(word) > 3]                                   # Remove Stopwords
  vocabulary = " ".join([char for char in wordWithoutStopwords if char not in string.punctuation ])                            # Remove Punctuations
  noContextualStopwords = remove_contextual_stopwords(vocabulary)                                                              # Remove Contextual Stopwords
  return noContextualStopwords.split()                                                                                         # Returning lemmatized-Vocabulary

## **Using Helper functions to clean the data**

In [21]:
df['cleaned_text'] = df['comment_text'].apply(regex_cleaning)  # Cleaning using Regex

In [22]:
df['cleaned_text'] = df['comment_text'].apply(only_eng)  # Selecting Only English words

## **Contextual Stop words**
- Creating a for loop to store all the comments into a single list:
- In terms of Preprocessing only steps used are remove words less than 3 characters and removed stopwords
- The result is stored in a dictionary, where key is word and value is frequency of the word. 
- This dictionary is convered into DataFrame to observe most frequent words and using that decision is made about selecting **Contextual Stop Words**

In [23]:
freq_dict ={}
text_list = [text for text in df['comment_text']]
for sentence in text_list:
  for word in sentence.split(): 
    
    if word in freq_dict.keys() and len(word) > 3 and word not in stopwords.words('english'):
      freq_dict[word] += 1

    if word not in freq_dict.keys() and len(word) > 3 and word not in stopwords.words('english'):
      freq_dict[word] = 1


count_df = pd.DataFrame( freq_dict.values(), freq_dict.keys()).reset_index().rename({0: "Frequency", "index": "Words"}, axis =1)
count_df.sort_values(by = 'Frequency', ascending = False)[:15]

Words  Frequency
14     article       1137
54       would        931
446       page        924
5         like        764
718       ass.        682
584       talk        652
684       fuck        592
94       think        589
570     Please        575
589  Wikipedia        544
800       know        500
29        This        464
188       also        453
6         edit        451
85      people        422

## **Observations:**
---
- We can clearly see that words like **page, wikipedia, edit** show up in top 15 words (in terms of frequency).
- We can easily call these words as **Contextual Stop-words** and remove such words from our corpus.
- Using Part of Speech, certain POS (Adjective, Pronoun, Number, Pronoun, Punctuation) words are removed as they are also be considered as **Contextual Stop Words** 

### **Using remove_contextual_stopwords function:**
---
- Remove Contextual words from corpus.


In [24]:
%%time
df['cleaned_text'] = df['comment_text'].apply(remove_contextual_stopwords) # Removing Contextual Stopwords

CPU times: user 4min 28s, sys: 1.96 s, total: 4min 29s
Wall time: 4min 31s


## **Let's check the most-frequent words now:**
- Same method as used above

In [25]:
freq_dict ={}
text_list = [text for text in df['cleaned_text']]
for sentence in text_list:
  for word in sentence.split(): 
    
    if word in freq_dict.keys() and len(word) > 3 and word not in stopwords.words('english'):
      freq_dict[word] += 1

    if word not in freq_dict.keys() and len(word) > 3 and word not in stopwords.words('english'):
      freq_dict[word] = 1


count_df = pd.DataFrame( freq_dict.values(), freq_dict.keys()).reset_index().rename({0: "Frequency", "index": "Words"}, axis =1)
count_df.sort_values(by = 'Frequency', ascending = False)[:15]

Words  Frequency
225          talk       1182
67          think        630
418          fuck        629
45           know        596
60         people        553
13           name        540
62           time        486
453        thanks        416
167         could        394
368   information        393
1024     deletion        391
189          make        391
57           good        377
2655         suck        375
961         image        367

## **Observation:**
- Above result actually makes sense. as most of our data is non-toxic comment, our data now shows that a few toxic words are present in the top 15 most frequenct words.


In [26]:
features = df['comment_text'].values
labels = df['toxic'].values

## **Let's Try BoW on subset of Data**

In [27]:
# Create BOW in SKlearn
wordVector = CountVectorizer(analyzer = final_preprocessing)

#Build the Vocabulary
finalWordVectorVocab = wordVector.fit(features[:10])

# # To create BOW
bagOfWords = finalWordVectorVocab.transform(features[:10])

In [28]:
print(finalWordVectorVocab.get_feature_names_out())

['abuse' 'account' 'admin' 'administrative' 'admitted' 'alex' 'american'
 'anyone' 'astrological' 'attends' 'attention' 'august' 'awards'
 'baranovichi' 'barnstar' 'began' 'behavior' 'belarus' 'belarusfilm'
 'best' 'block' 'born' 'brest' 'bring' 'call' 'called' 'can' 'castist'
 'categories' 'cause' 'celestia' 'certain' 'characters' 'child' 'children'
 'class' 'classes' 'close' 'committee' 'competition' 'continue'
 'contribute' 'contributing' 'could' 'course' 'creating' 'dating' 'deals'
 'dear' 'deceased' 'decided' 'defender' 'denied' 'deserve' 'diplomas'
 'disagree' 'discussion' 'dislike' 'divorced' 'drama' 'dumbhead'
 'dunechka' 'dzmitruk' 'editor' 'editors' 'ethinicty' 'expect' 'extreme'
 'family' 'father' 'featured' 'filtering' 'first' 'folloing' 'followed'
 'fordman' 'form' 'former' 'freak' 'free' 'frequency' 'front' 'good'
 'government' 'graduate' 'graduated' 'greater' 'group' 'guess' 'gwern'
 'gymnastics' 'hands' 'happy' 'harass' 'held' 'helsinki' 'high' 'higher'
 'hippie' 'hits'

## **Train-Test Split and instantiating TF-IDF Vectorizer:**
- Used **stratify = labels** in train_test_split so that imbalanced ratio is mentained in train-test-split.
- Used **max_features = 4000** to restrict the vocabulary to 4000.
- Used **min_df = 2** which selects only those words which atleast are seen 2 times.
- Fit and Transformed X_train and Transformed X_test

In [29]:
%%time
# Splitting the data into Training and Testing set
X_train, X_test, y_train, y_test = train_test_split(features, labels, stratify = labels,   test_size= 0.3,  random_state = 15)

#Create TF-IDF using TfidfVectorizer
tfidfVectorizer = TfidfVectorizer(analyzer= final_preprocessing, max_features = 4000, min_df = 2) # Instantiating Tfidfvectorizer
tfidfObject_train = tfidfVectorizer.fit_transform(X_train)                                        # Fit & transform on Training set
tfidfObject_test = tfidfVectorizer.transform(X_test)                                              # Transform the testing set
print(tfidfObject_train.shape, tfidfObject_test.shape)                                            # Checking Shape of training and testing set

(3500, 4000) (1500, 4000)
CPU times: user 3min 6s, sys: 886 ms, total: 3min 7s
Wall time: 3min 7s


## **Create first model: SVC**
- SVC model with kernel = "linear" which is used for binary classification.
- Class imbalance of label is not considered here.

In [30]:
model = SVC(kernel="linear")
model.fit(tfidfObject_train,y_train)

preds_train = model.predict(tfidfObject_train)                                            # Prediction on training set
preds_test = model.predict(tfidfObject_test)                                              # Prediction on training set

training_metrics = metrics.classification_report(y_train, preds_train)                    # Getting Classification report of Training set predictions
testing_metrics = metrics.classification_report(y_test, preds_test)                       # Getting Classification report of Test set predictions

print(f"Training Confusion Matrix: \n{metrics.confusion_matrix(y_train, preds_train)}\n") # Printing Confusion Matrix (training)
print(f"Training Classification Report: \n{training_metrics}")                            # Printing Classification report (testing)
print("="*100)
print(f"Testing Confusion Matrix: \n{metrics.confusion_matrix(y_test, preds_test)}\n")    # Printing Confusion Matrix (training)
print(f"Testing Classification Report: \n{testing_metrics}")                              # Printing Classification report (testing)

Training Confusion Matrix: 
[[3193    1]
 [ 128  178]]

Training Classification Report: 
              precision    recall  f1-score   support

           0       0.96      1.00      0.98      3194
           1       0.99      0.58      0.73       306

    accuracy                           0.96      3500
   macro avg       0.98      0.79      0.86      3500
weighted avg       0.96      0.96      0.96      3500

Testing Confusion Matrix: 
[[1366    3]
 [  74   57]]

Testing Classification Report: 
              precision    recall  f1-score   support

           0       0.95      1.00      0.97      1369
           1       0.95      0.44      0.60       131

    accuracy                           0.95      1500
   macro avg       0.95      0.72      0.78      1500
weighted avg       0.95      0.95      0.94      1500



## Observations:
- Model is not generalized, training_accuracy > testing_accuracy
- 0 = Non-Toxic, 1 = Toxic
- Observing Confusion matrix and Recall we can see that Model is classifying Non-toxic comments better than toxic comments, reason could be unbalanced data.
- Moreover model is predicting only 1 non-toxic comment as toxic comment, whereas it is predicting 128 toxic comments as non-toxic comments, which is not acceptable. Hence, imbalanced data needs to be taken care of.

## **Model with taking care of Imbalanced Data:**
- Using SVC again but this time using class_weight = 'balanced' which automatically takes care of the imbalanced class.
- kernal = 'linear' as we know is used for binary classification.

In [31]:
from sklearn.svm import SVC
model = SVC(kernel="linear", class_weight='balanced') #linear classifier
model.fit(tfidfObject_train,y_train)

preds_train = model.predict(tfidfObject_train)                                            # Prediction on training set
preds_test = model.predict(tfidfObject_test)                                              # Prediction on training set

training_metrics = metrics.classification_report(y_train, preds_train)                    # Getting Classification report of Training set predictions
testing_metrics = metrics.classification_report(y_test, preds_test)                       # Getting Classification report of Test set predictions

print(f"Training Confusion Matrix: \n{metrics.confusion_matrix(y_train, preds_train)}\n") # Printing Confusion Matrix (training)
print(f"Training Classification Report: \n{training_metrics}")                            # Printing Classification report (testing)
print("="*100)
print(f"Testing Confusion Matrix: \n{metrics.confusion_matrix(y_test, preds_test)}\n")    # Printing Confusion Matrix (training)
print(f"Testing Classification Report: \n{testing_metrics}")                              # Printing Classification report (testing)

Training Confusion Matrix: 
[[3138   56]
 [   9  297]]

Training Classification Report: 
              precision    recall  f1-score   support

           0       1.00      0.98      0.99      3194
           1       0.84      0.97      0.90       306

    accuracy                           0.98      3500
   macro avg       0.92      0.98      0.95      3500
weighted avg       0.98      0.98      0.98      3500

Testing Confusion Matrix: 
[[1325   44]
 [  45   86]]

Testing Classification Report: 
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1369
           1       0.66      0.66      0.66       131

    accuracy                           0.94      1500
   macro avg       0.81      0.81      0.81      1500
weighted avg       0.94      0.94      0.94      1500



## **Observations:**

---


- Model is not generalized, training_accuracy > testing_accuracy.
- 0 = Non-Toxic, 1 = Toxic
- Now the recall and f1-score has improved. Also we see that model is classifying toxic comments correctly as compared to previous model. 
- When observing Test-data classification report we see that 45 toxic comments are classified as non-toxic and 44 non-toxic comments are classified as toxic.
- Let's use Hyper-Parameter tuning to improve this score.


## **Let's Try Hyper Parameter Tuning on Second Model using Gridsearch CV**
- Using GridSearch and StratifiedKFold (for class imbalance)
- Only setting values for hyper-parameter 'C'
- Specifying class_weight = 'balanced' in SVC to allow model to decide the appropriate weights of imbalanced class.

### **After some permutations and combinations of parameters:**
- **Using recall as scoring reduces the accuracy of testing set, whereas setting up accuracy or f1 as scoring reduces recall.**
- Hence following code **scoring is set to recall and accuracy. Finally refit is set to recall, as that will be deciding scoring metrics.**


In [32]:
params = {'C': [0.01,0.01,0.05,0.5],                                   # Setting up parameter for SVC to be tried out in GridSearch CV
              # 'degree': [1,4,8]
          }                            
clf = SVC( kernel="linear", class_weight='balanced')                   # initializing SVC
model = GridSearchCV(clf, param_grid = params , cv=StratifiedKFold(5), # GridSearchCV with StratifedKfold and scoring = recall and f1, final decision = recall
                     scoring=['recall', 'f1'], refit='recall')
model.fit(tfidfObject_train,y_train)                                   # Fitting the GridSearchModel on training set

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=SVC(class_weight='balanced', kernel='linear'),
             param_grid={'C': [0.01, 0.01, 0.05, 0.5]}, refit='recall',
             scoring=['recall', 'f1'])

In [33]:
model.best_estimator_  # Best Estimator after applying GridsearchCV

SVC(C=0.01, class_weight='balanced', kernel='linear')

In [34]:
model.best_score_ # Best Score after appying GridSearchCV

0.8

### **Prediction using GridSearchCV model**

In [35]:
preds_train = model.predict(tfidfObject_train)                                            # Prediction on training set
preds_test = model.predict(tfidfObject_test)                                              # Prediction on training set

training_metrics = metrics.classification_report(y_train, preds_train)                    # Getting Classification report of Training set predictions
testing_metrics = metrics.classification_report(y_test, preds_test)                       # Getting Classification report of Test set predictions

print(f"Training Confusion Matrix: \n{metrics.confusion_matrix(y_train, preds_train)}\n") # Printing Confusion Matrix (training)
print(f"Training Classification Report: \n{training_metrics}")                            # Printing Classification report (testing)
print("="*100)
print(f"Testing Confusion Matrix: \n{metrics.confusion_matrix(y_test, preds_test)}\n")    # Printing Confusion Matrix (training)
print(f"Testing Classification Report: \n{testing_metrics}")                              # Printing Classification report (testing)

Training Confusion Matrix: 
[[3194    0]
 [ 291   15]]

Training Classification Report: 
              precision    recall  f1-score   support

           0       0.92      1.00      0.96      3194
           1       1.00      0.05      0.09       306

    accuracy                           0.92      3500
   macro avg       0.96      0.52      0.52      3500
weighted avg       0.92      0.92      0.88      3500

Testing Confusion Matrix: 
[[1369    0]
 [ 123    8]]

Testing Classification Report: 
              precision    recall  f1-score   support

           0       0.92      1.00      0.96      1369
           1       1.00      0.06      0.12       131

    accuracy                           0.92      1500
   macro avg       0.96      0.53      0.54      1500
weighted avg       0.92      0.92      0.88      1500



## **Observations:**

---
- Model is not generalized, training_accuracy > testing_accuracy (Overfitted model)
- 0 = Non-Toxic, 1 = Toxic
- As expected and written initially, the model doesnt perform good when we set deciding factor as recall. 
- Model has performed worse than than before **Recall of toxic comments  = 0.06 and f1-score = 0.12** for test-set.
- Let's try another approach to improve the result.

## **Another approach to improve the model:**
- Using **scoring = ['recall', 'f1']** which ensures both of these metrics will be considered.
- Finally using **refit = 'f1'** which ensures that finally f1-score will be considered as the deciding metrics for this model. 

In [36]:
params = {'C': [0.01,0.01,0.05,0.5,1]}                       # Setting up parameter for SVC to be tried out in GridSearch CV

clf = SVC( kernel="linear", class_weight='balanced',  )     # initializing SVC
model = GridSearchCV(clf, param_grid = params ,             # GridSearchCV with StratifedKfold and scoring = recall and f1, final decision = recall
                     cv=StratifiedKFold(5), 
                     scoring=['recall', 'f1'], refit='f1')
model.fit(tfidfObject_train,y_train)                        # Fitting the GridSearchModel on training set


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=SVC(class_weight='balanced', kernel='linear'),
             param_grid={'C': [0.01, 0.01, 0.05, 0.5, 1]}, refit='f1',
             scoring=['recall', 'f1'])

In [37]:
model.best_estimator_   # Best Estimator after applying GridsearchCV

SVC(C=1, class_weight='balanced', kernel='linear')

In [38]:
model.best_score_   # Best Score after appying GridSearchCV

0.5507821918853607

In [39]:
preds_train = model.predict(tfidfObject_train)                                            # Prediction on training set
preds_test = model.predict(tfidfObject_test)                                              # Prediction on training set

training_metrics = metrics.classification_report(y_train, preds_train)                    # Getting Classification report of Training set predictions
testing_metrics = metrics.classification_report(y_test, preds_test)                       # Getting Classification report of Test set predictions

print(f"Training Confusion Matrix: \n{metrics.confusion_matrix(y_train, preds_train)}\n") # Printing Confusion Matrix (training)
print(f"Training Classification Report: \n{training_metrics}")                            # Printing Classification report (testing)
print("="*100)
print(f"Testing Confusion Matrix: \n{metrics.confusion_matrix(y_test, preds_test)}\n")    # Printing Confusion Matrix (training)
print(f"Testing Classification Report: \n{testing_metrics}")                              # Printing Classification report (testing)

Training Confusion Matrix: 
[[3138   56]
 [   9  297]]

Training Classification Report: 
              precision    recall  f1-score   support

           0       1.00      0.98      0.99      3194
           1       0.84      0.97      0.90       306

    accuracy                           0.98      3500
   macro avg       0.92      0.98      0.95      3500
weighted avg       0.98      0.98      0.98      3500

Testing Confusion Matrix: 
[[1325   44]
 [  45   86]]

Testing Classification Report: 
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1369
           1       0.66      0.66      0.66       131

    accuracy                           0.94      1500
   macro avg       0.81      0.81      0.81      1500
weighted avg       0.94      0.94      0.94      1500



## **Observations:**

---
- Model is not generalized, training_accuracy > testing_accuracy 
- 0 = Non-Toxic, 1 = Toxic
- We see that model is predicting 45 toxic comments as non-toxic comments.
- Recall of non-toxic comments = 0.66 and f1-score = 0.66
- As we see that model is not improvising further. Hence, we can conclude this f1-score and recall as our final score.

### **Further approaches may include:**
- Using other ML or DL algorithms.
- Use other embeddings like word2vec etc. 

### **What are the most prominent terms in the toxic comments?**
- Separate the comments from the test set that the model identified as toxic
- Make one large list of the terms
- Get the top 15 terms



In [41]:
# np.concatenate((y_test, preds_test, X_test), axis = 1)
n_df = pd.DataFrame() 
n_df['comments'] = X_test
n_df['orginal_labels'] = y_test
n_df['predicted_labels'] = preds_test

In [42]:
list_of_toxic_comments_predicted = " ".join(n_df[n_df.predicted_labels == 1]['comments'].to_list()).split()

## **Frequency of Toxic Words without text-cleaning**

In [43]:
freq_dict ={}
text_list = list_of_toxic_comments_predicted
for word in text_list: 
    
    if word in freq_dict.keys() and len(word) > 3 and word not in stopwords.words('english'):
      freq_dict[word] += 1

    if word not in freq_dict.keys() and len(word) > 3 and word not in stopwords.words('english'):
      freq_dict[word] = 1


count_df = pd.DataFrame( freq_dict.values(), freq_dict.keys()).reset_index().rename({0: "Frequency", "index": "Words"}, axis =1)
count_df.sort_values(by = 'Frequency', ascending = False)[:15]

Words  Frequency
703      ass.        680
259      fuck        563
269  ass!Fuck        277
823   FUCKING         34
822     DON'T         33
820    MOTHER         32
824    PENIS!         32
821    FUCKER         32
819     CURPS         32
60       like         14
127     block         12
61    fucking         12
152      talk         12
100     think         10
211      Fuck         10

## **Frequency of Toxic Words after text-cleaning**

In [44]:
predicted_toxic_comments_cleaned = n_df[n_df.predicted_labels == 1]['comments'].apply(regex_cleaning)  # Cleaning using Regex
predicted_toxic_comments_cleaned = predicted_toxic_comments_cleaned.apply(remove_contextual_stopwords) # Removing Contextual Stopwords
toxic_comments =" ".join(predicted_toxic_comments_cleaned.to_list()).split()

In [45]:
freq_dict ={}
text_list = toxic_comments
for word in text_list: 
    
    if word in freq_dict.keys() and len(word) > 3 and word not in stopwords.words('english'):
      freq_dict[word] += 1

    if word not in freq_dict.keys() and len(word) > 3 and word not in stopwords.words('english'):
      freq_dict[word] = 1


count_df = pd.DataFrame( freq_dict.values(), freq_dict.keys()).reset_index().rename({0: "Frequency", "index": "Words"}, axis =1)
count_df.sort_values(by = 'Frequency', ascending = False)[:15]

Words  Frequency
164     fuck        853
49   fucking         45
589   fucker         35
323    penis         35
588   mother         33
587    curps         32
90     block         18
116     talk         13
127   people         12
86    stupid         11
132     life         11
601     hate         10
78     think         10
1       shit          9
81      know          9

## **PRs are welcome**